version: '3'
services:
  pdfy:
    container_name: pdfy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./public:/public"
      - "./.next:/.next"